### ISSUE TITLE
Deprecated selector in `spacemacs-dark-syntax/index.less`

### ISSUE THREAD

**Issue by AleCx4** [bcoop713/spacemacs-dark-syntax-atom#1]
In `spacemacs-dark-syntax/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor,
:host` => `atom-text-editor,atom-text-editor`

* `atom-text-editor .wrap-guide,
:host .wrap-guide` => `atom-text-editor .wrap-guide,atom-text-editor .wrap-guide`

* `atom-text-editor .indent-guide,
:host .indent-guide` => `atom-text-editor .indent-guide,atom-text-editor .indent-guide`

* `atom-text-editor .invisible-character,
:host .invisible-character` => `atom-text-editor .invisible-character,atom-text-editor .invisible-character`

* `atom-text-editor .line.cursor-line,
:host .line.cursor-line` => `atom-text-editor .line.cursor-line,atom-text-editor .line.cursor-line`

* `atom-text-editor .gutter,
:host .gutter` => `atom-text-editor .gutter,atom-text-editor .gutter`

* `atom-text-editor .gutter .line-number.cursor-line,
:host .gutter .line-number.cursor-line` => `atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line`

* `atom-text-editor .gutter .line-number.cursor-line-no-selection,
:host .gutter .line-number.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection`

* `atom-text-editor .gutter .line-number.folded,
:host .gutter .line-number.folded,
atom-text-editor .gutter .line-number:after,
:host .gutter .line-number:after,
atom-text-editor .fold-marker:after,
:host .fold-marker:after` => `atom-text-editor .gutter .line-number.folded,atom-text-editor .gutter .line-number.folded,
atom-text-editor .gutter .line-number:after,atom-text-editor .gutter .line-number:after,
atom-text-editor .fold-marker:after,atom-text-editor .fold-marker:after`

* `atom-text-editor .invisible,
:host .invisible` => `atom-text-editor .invisible,atom-text-editor .invisible`

* `atom-text-editor .cursor,
:host .cursor` => `atom-text-editor .cursor,atom-text-editor .cursor`

* `atom-text-editor .selection .region,
:host .selection .region` => `atom-text-editor .selection .region,atom-text-editor .selection .region`

* `atom-text-editor .search-results .marker .region,
:host .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region,atom-text-editor .search-results .syntax--marker .region`

* `atom-text-editor .search-results .marker.current-result .region,
:host .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region,atom-text-editor .search-results .syntax--marker.current-result .region`

* `.comment` => `.syntax--comment`

* `.keyword` => `.syntax--keyword`

* `.keyword.control` => `.syntax--keyword.syntax--control`

* `.keyword.operator` => `.syntax--keyword.syntax--operator`

* `.keyword.other.special-method` => `.syntax--keyword.syntax--other.syntax--special-method`

* `.keyword.other.unit` => `.syntax--keyword.syntax--other.syntax--unit`

* `.storage` => `.syntax--storage`

* `.constant` => `.syntax--constant`

* `.constant.character.escape` => `.syntax--constant.syntax--character.syntax--escape`

* `.constant.numeric` => `.syntax--constant.syntax--numeric`

* `.constant.other.color` => `.syntax--constant.syntax--other.syntax--color`

* `.constant.other.symbol` => `.syntax--constant.syntax--other.syntax--symbol`

* `.variable` => `.syntax--variable`

* `.variable.interpolation` => `.syntax--variable.syntax--interpolation`

* `.variable.parameter.function` => `.syntax--variable.syntax--parameter.syntax--function`

* `.invalid.illegal` => `.syntax--invalid.syntax--illegal`

* `.string` => `.syntax--string`

* `.string.regexp` => `.syntax--string.syntax--regexp`

* `.string.regexp .source.ruby.embedded` => `.syntax--string.syntax--regexp .syntax--source.syntax--ruby.syntax--embedded`

* `.string.other.link` => `.syntax--string.syntax--other.syntax--link`

* `.punctuation.definition.comment` => `.syntax--punctuation.syntax--definition.syntax--comment`

* `.punctuation.definition.string,
.punctuation.definition.variable,
.punctuation.definition.parameters,
.punctuation.definition.array` => `.syntax--punctuation.syntax--definition.syntax--string,
.syntax--punctuation.syntax--definition.syntax--variable,
.syntax--punctuation.syntax--definition.syntax--parameters,
.syntax--punctuation.syntax--definition.syntax--array`

* `.punctuation.definition.bold` => `.syntax--punctuation.syntax--definition.syntax--bold`

* `.punctuation.definition.italic` => `.syntax--punctuation.syntax--definition.syntax--italic`

* `.support.function` => `.syntax--support.syntax--function`

* `.support.function.any-method` => `.syntax--support.syntax--function.syntax--any-method`

* `.entity.name.function` => `.syntax--entity.syntax--name.syntax--function`

* `.entity.name.type` => `.syntax--entity.syntax--name.syntax--type`

* `.entity.other.inherited-class` => `.syntax--entity.syntax--other.syntax--inherited-class`

* `.entity.name.class,
.entity.name.type.class` => `.syntax--entity.syntax--name.syntax--class,
.syntax--entity.syntax--name.syntax--type.syntax--class`

* `.entity.name.section` => `.syntax--entity.syntax--name.syntax--section`

* `.entity.name.tag` => `.syntax--entity.syntax--name.syntax--tag`

* `.entity.other.attribute-name` => `.syntax--entity.syntax--other.syntax--attribute-name`

* `.entity.other.attribute-name.id` => `.syntax--entity.syntax--other.syntax--attribute-name.syntax--id`

* `.source.gfm .markup` => `.syntax--source.syntax--gfm .syntax--markup`

* `atom-text-editor[mini] .scroll-view,
:host([mini]) .scroll-view` => `atom-text-editor[mini] .scroll-view,atom-text-editor .scroll-view`

* `.html .entity.name,
.html .entity.tag` => `.syntax--html .syntax--entity.syntax--name,
.syntax--html .syntax--entity.syntax--tag`

* `.html .entity.attribute-name` => `.syntax--html .syntax--entity.syntax--attribute-name`

* `.html .string` => `.syntax--html .syntax--string`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by andrewbanchich** [comment]
@bcoop713 any plans for this?

**Comment by bobfp** [comment]
@andrewbanchich I would love to update it. I'm pretty swamped right now though if you want to create a PR.

**Comment by andrewbanchich** [comment]
@bcoop713 cool, i'll see what i can do.

**Comment by andrewbanchich** [comment]
@bcoop713 this should be resolved now in this pull request #2

**Comment by bobfp** [comment]
https://github.com/bcoop713/spacemacs-dark-syntax-atom/pull/2
